//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYM_Management_System_G.M.S_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductPlan()
        {
            this.ProductBuyings = new HashSet<ProductBuying>();
        }
    
        public int ProductPlanId { get; set; }
        public string ProductName { get; set; }
        public int ProductParPrice { get; set; }
        public int ProductSellPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBuying> ProductBuyings { get; set; }
    }
}
